xyjconfig:
   #标识日志数据库所在微服务,默认值为xyj-admin
  log-service-id: xyj-admin
   #生成ID使用,数据中心编码[雪花算法],每个微服务需不同,取值范围 0~31,默认值0
  datacenter-id: 0
   #生成ID使用,机器或进程编码[雪花算法],每个微服务需不同,取值范围 0~31,默认值0
  worker-id: 0
   #配置表格渲染时扫描的实体类，设置包名，可以设置多个包名
  scanmodel:
    - com.xyjsoft.admin.model
    
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8982
    
spring:
  application:
    name: xyj-admin
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://114.115.157.140:3306/hnoaprint?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=CTT
      username: root
      password: xyjsoft
      filters: stat,wall,slf4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    host: 114.115.157.140
    port: 6379
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    password: xyjsoft-admin_110_for-xym
    timeout: 10000 # 连接超时时间（毫秒）  
    lettuce: # springboot2.0后默认使用lettuce连接redis,底层使用的是netty框架做支撑
      pool:
         min-idle: 1 # 连接池中的最小空闲连接 默认 0
         max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-active: 20 # 连接池最大连接数（使用负值表示没有限制） 默认 8
         max-idle: 8 # 连接池中的最大空闲连接 默认 8
  #时间统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
     level:
         com.xyjsoft.admin.dao.* : debug
         io.swagger.models.parameters.AbstractSerializableParameter: error

eureka:
  client: #客户端注册进eureka服务列表内
    #表示eureka client间隔多久去拉取服务器注册信息,默认为30秒
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://114.115.157.140:8981/eureka/
  instance:
    ip-address: 114.115.157.140 #强制指定IP地址，否则默认会获取本机的IP地址
    instance-id: 114.115.157.140:${server.port}
    prefer-ip-address: true
  
#feign客户端启动hystrix断路保护
feign:
  hystrix: 
    enabled: true  
 
ribbon:
  ReadTimeout: 120000  #处理超时时间 默认5秒
  ConnectTimeout: 120000 #连接超时时间 默认2秒
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1

  #eager-load:
  #  enabled: true
  #  clients:
  #    - xyj-hnoa-master
 
hystrix:
  command: 
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 120000 #断路切换超时
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      
# pagehelper   
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  resHost: 122.114.70.54
  storagePort: 8000
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 122.114.70.54:22122
    
# wxcore


swagger:
     production: false #线上环境，true时屏蔽swagger
     basic: 
         enable: false #为true时，启用用户名密码验证
         username: hxsh
         password: xyjsoft
     info:
         description: 网关api
         title: 新永丰智能打印平台API
         author: 河南讯宜捷科技有限公司
      