xyjconfig:
  #restTemplate请求超时时间
  restTemplateTimeOut: 50000
  #不使用图片服务器情况下访问上传的图片地址,确保配置路径下的文件夹内容可以访问
  uploadAddress: http://192.168.3.111:8011/
  mqtt:
     #false:停用,true: 启用
     stopstate: true
     #用户名
     username: admin
     #密码
     password: public
     #MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613，tcp://192.168.2.133:61613
     url: tcp://114.116.236.214:9002
     #连接服务器默认客户端ID
     #clientid: admin
     #默认消息订阅主题，如果有多个可用逗号分割
     defaultTopic: $WFW/${spring.application.name}
     #连接超时，秒为单位
     connectionTimeout: 3000
     #心跳间隔时间，秒为单位
     keepAlive: 60
     #消息发送超时时间，毫秒单位，0：永久等待
     publishCompleteTimeOut: 0
     #消息并发最大数
     maxInflight: 10
     #0：最多一次的传输 1：至少一次的传输，(鸡肋)2： 只有一次的传输
     qos: 2
     #true：消息服务器保留最后一条消息，false:不保留消息
     retained: true
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 7001
   
spring:
  application:
    name: xyj-admin
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://49.4.64.158:3306/xyj-base-m2?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=CTT
      username: root
      password: xyjsoft
       # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j,config
      max-active: 100
      initial-size: 1
       # 配置获取连接等待超时的时间
      max-wait: 60000
      min-idle: 1
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
       #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

logging:
  file: /var/log/admin.log
  level:
    com.xyjsoft.admin.dao.* : debug
    io.swagger.models.parameters.AbstractSerializableParameter: error

swagger:
  production: false #线上环境，true时屏蔽swagger
  basic: 
     enable: false #为true时，启用用户名密码验证
     username: xyjsoft
     password: xyjsoft
  info:
    description: 讯宜捷平台
    title: 讯宜捷数据中心
    author: admin