xyjconfig:
   #标识日志数据库所在微服务,默认值为xyj-admin
  log-service-id: xyj-admin
   #生成ID使用,数据中心编码[雪花算法],每个微服务需不同,取值范围 0~31,默认值0
  datacenter-id: 0
   #生成ID使用,机器或进程编码[雪花算法],每个微服务需不同,取值范围 0~31,默认值0
  worker-id: 0
   #配置表格渲染时扫描的实体类，设置包名，可以设置多个包名
  scanmodel:
    - com.xyjsoft.admin.model
  mqtt:
     #false:停用,true: 启用
     stopstate: false
     #用户名
     username: admin
     #密码
     password: public
     #MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613，tcp://192.168.2.133:61613
     url: tcp://114.116.236.214:9002
     #连接服务器默认客户端ID
     #clientid: admin
     #默认消息订阅主题，如果有多个可用逗号分割
     defaultTopic: $WFW/xyjadmin
     #连接超时，秒为单位
     connectionTimeout: 3000
     #心跳间隔时间，秒为单位
     keepAlive: 60
     #消息发送超时时间，毫秒单位，0：永久等待
     publishCompleteTimeOut: 0
     #消息并发最大数
     maxInflight: 10
     #0：最多一次的传输 1：至少一次的传输，(鸡肋)2： 只有一次的传输
     qos: 2
     #true：消息服务器保留最后一条消息，false:不保留消息
     retained: true
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 7001
   
spring:
  application:
    name: xyj-admin
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://49.4.64.158:3306/xyj-base-m2?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=CTT
      username: root
      password: xyjsoft
       # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j,config
      max-active: 100
      initial-size: 1
       # 配置获取连接等待超时的时间
      max-wait: 60000
      min-idle: 1
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
       #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      
  redis:
    host: 49.4.64.158
    port: 6379
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    password: xyjsoft-admin_110_for-xym
    timeout: 10000 # 连接超时时间（毫秒）  
    lettuce: # springboot2.0后默认使用lettuce连接redis,底层使用的是netty框架做支撑
      pool:
         min-idle: 1 # 连接池中的最小空闲连接 默认 0
         max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-active: 20 # 连接池最大连接数（使用负值表示没有限制） 默认 8
         max-idle: 8 # 连接池中的最大空闲连接 默认 8
  #时间统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        serviceName: ${spring.application.name}
logging:
  file: /var/log/admin.log
  level:
    com.xyjsoft.admin.dao.* : debug
    io.swagger.models.parameters.AbstractSerializableParameter: error
eureka:
  client: #客户端注册进eureka服务列表内
    #表示eureka client间隔多久去拉取服务器注册信息,默认为30秒
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/
  instance:
    ip-address: 127.0.0.1 #强制指定IP地址，默认会获取本机的IP地址
    instance-id: 127.0.0.1:${server.port}
    prefer-ip-address: true
    health-check-url-path: /actuator/health   #应用实例的相对运行状况检查URL路径默认为 /info/health

  boot:
    admin:
      client:
        url: "http://127.0.0.1:7080"
        
#feign客户端启动hystrix断路保护
feign:
  hystrix: 
    enabled: true 
ribbon:
  ReadTimeout: 120000  #处理超时时间 默认5秒
  ConnectTimeout: 120000 #连接超时时间 默认2秒
  #MaxAutoRetries: 0
  #MaxAutoRetriesNextServer: 1
  
  #eager-load:
  #  enabled: true
  #  clients:
  #    - xyj-hnoa-master
hystrix:
  command: 
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 120000 #断路切换超时
              
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# pagehelper   
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  resHost: 39.96.75.66
  storagePort: 8000
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 172.17.74.101:22122
    
swagger:
  production: false #线上环境，true时屏蔽swagger
  basic: 
     enable: false #为true时，启用用户名密码验证
     username: xyjsoft
     password: xyjsoft
  info:
    description: 讯宜捷平台
    title: 讯宜捷数据中心
    author: admin